# Stage 1: Build
FROM golang:1.25 AS builder

WORKDIR /app

ENV CGO_ENABLED=0

COPY go.mod ./
COPY go.sum* ./

RUN go mod download

COPY . .

RUN go build -o main .

# Stage 2: Runtime
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .

RUN adduser -D appuser
USER appuser

EXPOSE 8080

CMD ["./main"]